package jni
//
//import "syscall"
//
//var (
//	jvm                          *syscall.LazyDLL
//	AttachCurrentThread          *syscall.LazyProc
//	AttachCurrentThreadAsDaemon  *syscall.LazyProc
//	GetEnv                       *syscall.LazyProc
//	GetObjectRefType             *syscall.LazyProc
//	GetJavaVM                    *syscall.LazyProc
//	DestroyJavaVM                *syscall.LazyProc
//	DetachCurrentThread          *syscall.LazyProc
//	FindClass                    *syscall.LazyProc
//	GetVersion                   *syscall.LazyProc
//	FromReflectedMethod          *syscall.LazyProc
//	FromReflectedField           *syscall.LazyProc
//	ToReflectedMethod            *syscall.LazyProc
//	GetSuperclass                *syscall.LazyProc
//	IsAssignableFrom             *syscall.LazyProc
//	ToReflectedField             *syscall.LazyProc
//	Throw                        *syscall.LazyProc
//	ThrowNew                     *syscall.LazyProc
//	ExceptionOccurred            *syscall.LazyProc
//	ExceptionDescribe            *syscall.LazyProc
//	ExceptionClear               *syscall.LazyProc
//	FatalError                   *syscall.LazyProc
//	PushLocalFrame               *syscall.LazyProc
//	PopLocalFrame                *syscall.LazyProc
//	NewGlobalRef                 *syscall.LazyProc
//	DeleteGlobalRef              *syscall.LazyProc
//	DeleteLocalRef               *syscall.LazyProc
//	IsSameObject                 *syscall.LazyProc
//	NewObjectA                   *syscall.LazyProc
//	GetObjectClass               *syscall.LazyProc
//	IsInstanceOf                 *syscall.LazyProc
//	GetMethodID                  *syscall.LazyProc
//	CallObjectMethodA            *syscall.LazyProc
//	CallBooleanMethodA           *syscall.LazyProc
//	CallCharMethodA              *syscall.LazyProc
//	CallShortMethodA             *syscall.LazyProc
//	CallIntMethodA               *syscall.LazyProc
//	CallLongMethodA              *syscall.LazyProc
//	CallFloatMethodA             *syscall.LazyProc
//	CallDoubleMethodA            *syscall.LazyProc
//	CallVoidMethodA              *syscall.LazyProc
//	CallNonvirtualObjectMethodA  *syscall.LazyProc
//	CallNonvirtualBooleanMethodA *syscall.LazyProc
//	CallNonvirtualByteMethodA    *syscall.LazyProc
//	CallNonvirtualIntMethodA     *syscall.LazyProc
//	CallNonvirtualLongMethodA    *syscall.LazyProc
//	CallNonvirtualFloatMethodA   *syscall.LazyProc
//	CallNonvirtualDoubleMethodA  *syscall.LazyProc
//	CallNonvirtualCharMethodA    *syscall.LazyProc
//	GetFieldID                   *syscall.LazyProc
//	GetObjectField               *syscall.LazyProc
//	GetBooleanField              *syscall.LazyProc
//	GetByteField                 *syscall.LazyProc
//	GetCharField                 *syscall.LazyProc
//	GetShortField                *syscall.LazyProc
//	GetIntField                  *syscall.LazyProc
//	GetLongField                 *syscall.LazyProc
//	GetFloatField                *syscall.LazyProc
//	GetDoubleField               *syscall.LazyProc
//	SetObjectField               *syscall.LazyProc
//	SetBooleanField              *syscall.LazyProc
//	SetByteField                 *syscall.LazyProc
//	SetCharField                 *syscall.LazyProc
//	SetShortField                *syscall.LazyProc
//	SetIntField                  *syscall.LazyProc
//	SetLongField                 *syscall.LazyProc
//	SetFloatField                *syscall.LazyProc
//	SetDoubleField               *syscall.LazyProc
//)
